name: Repository Check

on: [ push ]

jobs:

  container:
    runs-on: ubuntu-latest
    container: opentosca/winery-cli:latest
    steps:
      - uses: actions/checkout@v2
      - run: winery -cd --path $GITHUB_WORKSPACE
